# ${project.name} v${project.version}
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2014

# スラスターの上昇方向のスピードです
upperPower: 0.5

# スラスターの横方向のスピードです
sidePower: 3.0

# スラスターのアイテムです。足に装備できるものにしてください
thrusterMaterial: GOLD_BOOTS

# スラスターを噴射したときに、アイテムの耐久値をいくつ減らすかを設定します。
# 0なら、耐久値は減りません。
decreaseDurability: 2

# プレイヤーが接地していないときに、スラスターの使用を制限するかを設定します。
# true: 地面に立っているときのみスラスターが使用できます。
# false: いつでも使用できます。空中ジャンプができるようになります。
limitOnGround: true
